version: 2

build:
    os: "ubuntu-22.04"
    tools:
        python: "mambaforge-latest"
    jobs:
        post_checkout:
            - git fetch --unshallow || true

conda:
    environment: docs/environment-sphinx.yml
